{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: {{ include "fastapi-chassis.capabilities.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "fastapi-chassis.fullname" . }}
  namespace: {{ include "fastapi-chassis.namespace" . }}
  labels:
    {{- include "fastapi-chassis.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fastapi-chassis.selectorLabels" . | nindent 6 }}
{{- end }}
